{{- range .Values.certs }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "name" $ }}-{{ .name }}
  namespace: {{ include "ns" $ }}
spec:
  secretName: {{ include "name" $ }}-{{ .name }}-cert
  {{- if .annotations }}
  secretTemplate:
    annotations:
      {{- toYaml .annotations | nindent 6 }}
  {{- end }}
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: {{ .issuer.name | quote }}
    {{- if eq .issuer.type "cluster" }}
    kind: ClusterIssuer 
    {{- else }}
    kind: Issuer 
    {{- end }}
  dnsNames:
  {{- range .urls }}
  - {{ . | quote }}
  {{- end }}
---
{{- end }}