{{- range .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" (list $ .name) }}
  namespace: {{ include "ns" $ }}
data:
{{- range $k, $v := .data }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
---
{{- end }}