{{- range .Values.issuers }}
{{- if eq .type "cluster" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "name" $ }}-{{ .name }}
{{- else }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "name" $ }}-{{ .name }}
  namespace: {{ include "ns" $ }}
{{- end }}
spec:
{{- if eq .selfsigned "enable" }}
  selfSigned: {}
---
{{- else if .http }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ include "name" $ }}-{{ .name }}
    solvers:
    - http01:
        ingress:
          class: {{ .http.ingress }}
---
{{- else if .aws }}
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ include "name" $ }}-{{ .name }}
    solvers:
    - dns01:
        route53:
          region: {{ .aws.region }}
          accessKeyID: {{ .aws.access_key }}
          secretAccessKeySecretRef:
            name: {{ include "name" $ }}-{{ .name }}
            key: aws-secret-access-key
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "name" $ }}-{{ .name }}
  namespace: {{ include "ns" $ }}
data:
  aws-secret-access-key: {{ .aws.secret_key | b64enc }}
---
{{- end }}
{{- end }}
