{{- range .Values.rbac }}
{{- if eq .type "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
rules:
{{ toYaml .rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
---
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
rules:
{{ toYaml .rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "name" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" $ }}
  namespace: {{ include "ns" $ }}
---
{{- end }}
{{- end }}