{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" $ }}-{{ .name }}
  namespace: {{ include "ns" $ }}
{{- if not .type }}
type: Opaque
{{- else }}
type: {{ .type }}
{{- end }}
data:
{{- range $k, $v := .data }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
---
{{- end }}